configs:
  cm:
    url: https://argocd.timebertt.dski23a.timebertt.dev

server:
  insecure: false
  
  ingress:
    enabled: true
    ingressClassName: nginx   # or traefik, istio, etc.
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - argocd.timebertt.dski23a.timebertt.dev
    tls:
      - hosts:
          - argocd.timebertt.dski23a.timebertt.dev
        secretName: argocd-tls
    