mode: standalone
replicas: 1

auth:
  rootUser: minioadmin
  rootPassword: miniosecret

global:
  security:
    allowInsecureImages: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
  accessModes:
    - ReadWriteOnce

# image:
#   registry: docker.io
#   repository: bitnami/minio
#   tag: 2024.3.15-debian-12-r0

# console:
#   image:
#     registry: docker.io
#     repository: bitnami/minio-object-browser
#     tag: 2.1.0-debian-12-r0

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: minio.timebertt.dski23a.timebertt.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
  extraTls:
    - hosts:
        - minio.timebertt.dski23a.timebertt.dev
      secretName: minio-tls

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
